### ISSUE TITLE
lazy(date)

### ISSUE THREAD

**Issue by matthieugomez** [hadley/lazyeval#18]
`lazy(date)` returns a lazy object with expression "lazyLoadDBfetch(c(250834L, 107L), datafile, compressed, envhook)" and not date. Is there a way around this?

**Comment by dpastoor** [comment]
Don't know if this was supposedly resolved as it is closed, but I am also running into this issue with the variable `time` when I need to use it to capture it in cases when it refers to a column name.  Using force works but seems both inelegant and difficult to hedge for all scenarios (eg any time need to use this to capture for later use in dplyr internally would need to add force just in case).

**Comment by dpastoor** [comment]
actually this ends up breaking any functionality. For an example function where a dataframe and then two columns, one for time, and the other for some dependent variable

```
s_pauc <- function(df, time, dv) {

  time <- lazyeval::lazy(force(time))
  dv <- lazyeval::lazy(dv)
```

this will get around the situations where the data frame has `time` as a column name, but if the columns name is `Time` it will fail as `force(time)` is what is captured rather than `Time` so now I am unsure how to get around this.
