### ISSUE TITLE
all_dots() and coercion of character values

### ISSUE THREAD

**Issue by krlmlr** [hadley/lazyeval#90]
Consider the following use case:

```r
data_frame(`Column 1` = 1) %>% group_by_("Column 1")
```

The all_dots() call from group_by_.data.frame gives an incomprehensible error about parsing. The correct code is

```r
data_frame(`Column 1` = 1) %>% group_by_("`Column 1`")
```

or

```r
data_frame(`Column 1` = 1) %>% group_by_(as.name("Column 1"))
```

but this is so easy to get wrong, and as.name() is not vectorized. What can we do to help the user in this case?

This came up in the discussion of https://github.com/hadley/dplyr/issues/2224.

**Comment by zeehio** [comment]
This is my current solution, probably you already had considered it:

```r
# Set up a problem:
data(iris)
colnames(iris)[1] <- "evil`column"
colnames(iris)[2] <- "more evil`column" # MUAHAHA
# With a solution:
dplyr::select_(iris, .dots = lapply(c("evil`column", "more evil`column"), as.name))
```

**Comment by zeehio** [comment]
To my understanding, lazyeval treats characters as R expressions. This means that "a + b" or "my column name" are treated identically, and that is fine.

So I would say that lazyeval is doing the right thing and it should be the dplyr functions  -- because they are the ones that know that `group_by_`, `select_`, ... work with column names -- the ones converting those character expressions to names (also called symbols), so lazyeval can understand that they are not R expressions.

**Comment by krlmlr** [comment]
I agree that this probably isn't a lazyeval problem.
